"""Assemble dashboard/index.html from the modules in dashboard/assets/.

Why a build step for a static page: `index.html` has to keep working from `file://`
(CLAUDE.md, doc/dashboard.md — no server, no npm), and ES modules don't. A browser
refuses `import` over a file:// origin for the same CORS reason replay.html can't
`fetch()` its payload there. So the modules are concatenated into one inline
<script> rather than linked, and the assets stay the source of truth.

Same shape as vis/page.py: a skeleton with @@SLOT@@ markers, filled from assets/.

    python3 dashboard/build_page.py      # rebuild dashboard/index.html

Edit the files in dashboard/assets/, never index.html — it is generated.
"""

from pathlib import Path

ASSETS = Path(__file__).resolve().parent / "assets"
OUT = Path(__file__).resolve().parent / "index.html"

# Concatenation order is load order, so this list IS the dependency order: state
# first (everything reads the lineup), main last (it wires up and starts).
MODULES = [
    "state.js",      # lineup state, cap maths, DK roster rules
    "pool.js",       # pool tables, lineup panel, race-intel notes
    "sim.js",        # one random race outcome + DK scoring
    "optimize.js",   # candidate enumeration and evaluation
    "chances.js",    # per-pick probabilities and explanation
    "auto.js",       # Auto-sim tab
    "ai.js",         # AI-sim tab
    "quali.js",      # qualifying/grid entry
    "main.js",       # single-race sim, sort binding, startup
]


def build() -> Path:
    html = (ASSETS / "index.html").read_text(encoding="utf-8")
    css = (ASSETS / "dashboard.css").read_text(encoding="utf-8").rstrip()
    js = "\n".join(
        f"// ── {name} {'─' * max(0, 68 - len(name))}\n"
        + (ASSETS / name).read_text(encoding="utf-8").rstrip()
        for name in MODULES
    )

    for token, value in (("@@CSS@@", css), ("@@JS@@", js)):
        if token not in html:
            raise ValueError(f"assets/index.html has no {token} slot")
        html = html.replace(token, value)
    left = [s for s in html.split("@@")[1::2] if s.isupper()]
    if left:
        raise ValueError(f"unfilled slots in assets/index.html: {left}")

    banner = ("<!-- GENERATED by dashboard/build_page.py from dashboard/assets/ — "
              "do not edit; edit the assets instead. -->\n")
    OUT.write_text(banner + html, encoding="utf-8")
    return OUT


def main():
    out = build()
    kb = out.stat().st_size / 1024
    print(f"Wrote {out} ({kb:.0f} KB) from {len(MODULES)} modules + dashboard.css")


if __name__ == "__main__":
    main()
